apiVersion: v1
kind: Secret
metadata:
  name: clusternet-hub-proxy
  namespace: clusternet-system
  annotations:
    kubernetes.io/service-account.name: clusternet-hub-proxy
type: kubernetes.io/service-account-token
