apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: meta
  namespace: default
spec:
  repo: oci://635304352795.dkr.ecr.cn-north-1.amazonaws.com.cn
  chart: metadata
  version: 0.1.0
  targetNamespace: xxx
  chartPullSecret:
    name: ecr
    namespace: default
