
apiVersion: apps.clusternet.io/v1alpha1
kind: Globalization
metadata:
  name: nginx-global-overrides-demo
spec:
  # Priority is an integer defining the relative importance of this Globalization compared to others.
  # Lower numbers are considered lower priority.
  # Override values in lower Globalization will be overridden by those in higher Globalization.
  # (Optional) Default priority is 500.
  priority: 600
  feed:
    apiVersion: apps/v1
    kind: Deployment
    name: my-nginx
    namespace: foo
  overrides: # defines all the overrides to be processed with
    - name: add-update-labels
      type: MergePatch
      # Value is a YAML/JSON format patch that provides MergePatch to current resource defined by feed.
      # This override adds or updates some labels.
      value: |-
        metadata:
          labels:
            some-label: some-value
            another-label: another-value
    - name: remove-labels
      type: MergePatch
      # Value is a YAML/JSON format patch that provides MergePatch to current resource defined by feed.
      # This override removes some labels.
      # The value here can also be in json format.
      value: '{"metadata":{"labels":{"another-label":null,"some-other-label":null}}}'
